services:
  - type: web
    name: monacap-frontend
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_FIREBASE_API_KEY
        value: ${REACT_APP_FIREBASE_API_KEY}
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: ${REACT_APP_FIREBASE_PROJECT_ID}
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      - key: REACT_APP_FIREBASE_APP_ID
        value: ${REACT_APP_FIREBASE_APP_ID}
      - key: REACT_APP_BACKEND_URL
        value: ${REACT_APP_BACKEND_URL}
